# Generated by Django 6.1 on 2026-09-08 15:29

from django.conf import settings
from django.db import migrations


def backfill_project_owner(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    database_alias = schema_editor.connection.alias
    orphan_projects = Project.objects.using(database_alias).filter(owner__isnull=True)

    if not orphan_projects.exists():
        return

    legacy_owner, created = User.objects.using(database_alias).get_or_create(
        username="__legacy_owner__",
        defaults={"password": "!", "is_active": False},
    )

    if not created and (legacy_owner.password != "!" or legacy_owner.is_active):
        raise RuntimeError(
            "The __legacy_owner__ username is already used by a non-technical account."
        )

    orphan_projects.update(owner=legacy_owner)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_owner"),
    ]

    operations = [
        migrations.RunPython(
            backfill_project_owner,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
