# Generated by Django 6.1 on 2026-10-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_require_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='task_status_valid',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
